version: '3'
services:

  weather-analyzer-service:
    container_name: weather-analyzer-app
    image: viktorshilay/weather-analyzer-app
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:5432/weather_db
      X-RapidAPI-Key: 3d01127322msh1a2e27f642dc1d5p164ea1jsnad2a44421a29
    depends_on:
      - postgres-service

  postgres-service:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: weather_db
